import Home from './Home'
import Laptop from './laptop/Laptop'
import ProductDetail from './detail/ProductDetail'
import Section from './section/Section'
import Accessory from './accessory/Accessory'
import NotFound from './notFound/NotFound'
import LaptopByCate from './category/LaptopByCate'
import AccessoryDetail from './accessory/AccessoryDetail'
import SearchProduct from './search/SearchProduct'
export { Home, Laptop, ProductDetail, NotFound, Accessory, Section, LaptopByCate, AccessoryDetail, SearchProduct }
