import Header from './header/Header'
import Loading from './loading/Loading'
import Slider from './slider/Slider'
import Product from './product/Product'
import Footer from './footer/Footer'
import FooterBanner from './footer/FooterBanner'
import TableTechnique from './table/TableTechnique'
import AccessoryItem from './accessory/AccessoryItem'
import Modal from './modal/Modal'
import ViewMore from './view_more/ViewMore'
import Input from './input/Input'
import Breadcrumb from './breadcrumb/Breadcrumb'
export { Header, ViewMore, Loading, Breadcrumb, Slider, Input, Product, Footer, FooterBanner, TableTechnique, AccessoryItem, Modal }
